### PR TITLE
Updated architecture with GCP support.

### PR DESCRIPTION
**Pull request by arunpamulapati**

### CODE REVIEW

**Comment by arunpamulapati** [comment]
Please review the updated architecture diagram with GCP. Also cleaner formatting.

**Review by alexott — APPROVED** [review]
looks good

**Review by alexott — APPROVED** [review]

**Review by alexott — APPROVED** [review]
lgtm

**Comment by arunpamulapati** [comment]
Completed architecture merge with GCP update.

**Pull request merged**
