### PR TITLE
Databricks Splunk Integration v1.2.0 Library changes.

### PR DESCRIPTION
**Pull request by madhavpandya-cds**
- Updated "splunklib" library.
- Added "pycryptodom" library for custom encryption.

### CODE REVIEW

**Review by alexott — CHANGES_REQUESTED** [review]
tests need to be fixed

**Comment by alexott** [comment]
Please fix test: it should be autospec instead of auto_spec

**Review by nfx — CHANGES_REQUESTED** [review]
tests are required to be fixed

**Comment by alexott** [comment]
Close in favor of #40

**Pull request closed without merging**
